repos:
- repo: local
  hooks:
  - id: gitleaks
    name: Check for secrets with gitleaks
    entry: python ./install-gitleaks.py
    language: python
    types: [python]
# - repo: https://github.com/gitleaks/gitleaks
#   rev: v8.18.2
#   hooks:
#   - id: gitleaks